import type { Metadata, Viewport } from "next";
import { cookies } from "next/headers";
import "@fontsource-variable/fraunces/soft.css";
import "@fontsource-variable/nunito";
import { Peach } from "@/components/illustrations/buddies";
import { MotionProvider } from "@/components/motion-provider";
import { ServiceWorkerRegister } from "@/components/sw-register";
import splashScreens from "@/lib/splash-screens.json";
import { THEME_COOKIE, themeClass } from "@/lib/theme";
import "./globals.css";

export const metadata: Metadata = {
  title: { default: "GlucoPerso", template: "%s · GlucoPerso" },
  description: "Ton carnet de repas et d'insuline, tout en douceur.",
  applicationName: "GlucoPerso",
  robots: { index: false, follow: false },
  // favicon.ico and manifest.webmanifest come from the app/ file conventions.
  icons: {
    icon: [{ url: "/icons/icon-192.png", type: "image/png", sizes: "192x192" }],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  appleWebApp: {
    capable: true,
    title: "GlucoPerso",
    statusBarStyle: "default",
    // Generated by `npm run icons` (scripts/generate-icons.mjs).
    startupImage: splashScreens.map(({ width, height, ratio }) => ({
      url: `/splash/splash-${width * ratio}x${height * ratio}.png`,
      media: `(device-width: ${width}px) and (device-height: ${height}px) and (-webkit-device-pixel-ratio: ${ratio}) and (orientation: portrait)`,
    })),
  },
  // Older iOS versions only read the vendor-prefixed name.
  other: { "apple-mobile-web-app-capable": "yes" },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fbf4ea" },
    { media: "(prefers-color-scheme: dark)", color: "#17122a" },
  ],
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const theme = (await cookies()).get(THEME_COOKIE)?.value;
  return (
    <html lang="fr" className={themeClass(theme)}>
      <body>
        {/* Desktop only: a little signature on the desk, next to the notebook. */}
        <div
          aria-hidden="true"
          className="pointer-events-none fixed top-8 left-10 hidden items-center gap-3 lg:flex"
        >
          <Peach className="w-11" mood="happy" />
          <span className="font-display text-2xl font-semibold text-ink">GlucoPerso</span>
        </div>
        <MotionProvider>{children}</MotionProvider>
        <ServiceWorkerRegister />
      </body>
    </html>
  );
}
